export const SET_PROFILE = 'SET_PROFILE';
export const SET_CURRENT_SCREEN = 'SET_CURRENT_SCREEN';

export const FETCH_TIPS_LOADING = 'FETCH_TIPS_LOADING';
export const FETCH_TIPS_SUCCESS = 'FETCH_TIPS_SUCCESS';
export const FETCH_TIPS_FAILURE = 'FETCH_TIPS_FAILURE';

export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS';

export const SAVE_TIP = 'SAVE_TIP';
export const REMOVE_TIP = 'REMOVE_TIP';